/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pbo_final_boss;


import pbo_final_boss.model.Soal.Grade;
import pbo_final_boss.model.Soal.PaketSoal;
import pbo_final_boss.model.Soal.Soal;
import pbo_final_boss.model.User.Admin;
import pbo_final_boss.model.User.Dosen;
import pbo_final_boss.model.User.Mahasiswa;
import pbo_final_boss.util.HibernateUtil;
import pbo_final_boss.view.LoginView;
import pbo_final_boss.view.RegisView;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        org.hibernate.Session session = HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();

        Admin adm1 = new Admin("DWM", "Agung", "123123", "admin");
        Mahasiswa msh1 = new Mahasiswa("Mulyono", "123123", "mahasiswa", "098765", "Mulyono", "S1 IT", null,
                "mulyono@gmail.com");
        Dosen dsn1 = new Dosen("Tanto", "123123", "dosen", "87654", "tanto", "PBO", null, "tanto@gmail.com");
        LoginView view1 = new LoginView();
        view1.setVisible(true);
        RegisView view2 = new RegisView();
        view2.setVisible(false);
        
        session.persist(msh1);
        session.persist(dsn1);
        session.persist(adm1);

        session.getTransaction().commit();
        session.close();
    }
}
